source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.0'

target 'UnityFramework' do
  pod 'Firebase/Auth', '7.11.0'
  pod 'Firebase/Core', '7.11.0'
  pod 'Firebase/Database', '7.11.0'
  pod 'Firebase/Functions', '7.11.0'
  pod 'Firebase/Messaging', '7.11.0'
  pod 'Firebase/Storage', '7.11.0'
end
target 'Unity-iPhone' do
end
use_frameworks!
